/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'interview' : IDL.Null,
  'rejected' : IDL.Null,
  'reviewed' : IDL.Null,
  'offered' : IDL.Null,
});
export const JobRole = IDL.Variant({
  'fullStackDeveloper' : IDL.Null,
  'securityEngineer' : IDL.Null,
  'cybersecurityAnalyst' : IDL.Null,
  'softwareEngineer' : IDL.Null,
  'networkEngineer' : IDL.Null,
  'dataScientist' : IDL.Null,
});
export const Time = IDL.Int;
export const GpsCoordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const JobApplication = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'role' : JobRole,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'locationLabel' : IDL.Opt(IDL.Text),
  'coverNote' : IDL.Text,
  'location' : IDL.Opt(GpsCoordinates),
  'resumeUrl' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const VisitorLog = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Opt(IDL.Float64),
  'locationAccess' : IDL.Bool,
  'longitude' : IDL.Opt(IDL.Float64),
  'timestamp' : Time,
  'userAgent' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockEmail' : IDL.Func([IDL.Text], [], []),
  'getAllApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
  'getBlockedEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTotalApplications' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitorLogs' : IDL.Func([], [IDL.Vec(VisitorLog)], ['query']),
  'isAcceptingApplications' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEmailBlocked' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'logVisitorLocation' : IDL.Func([IDL.Float64, IDL.Float64, IDL.Text], [], []),
  'logVisitorNoLocation' : IDL.Func([IDL.Text], [], []),
  'resetAdminClaim' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAcceptingApplications' : IDL.Func([IDL.Bool], [], []),
  'submitApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        JobRole,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'unblockEmail' : IDL.Func([IDL.Text], [], []),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'interview' : IDL.Null,
    'rejected' : IDL.Null,
    'reviewed' : IDL.Null,
    'offered' : IDL.Null,
  });
  const JobRole = IDL.Variant({
    'fullStackDeveloper' : IDL.Null,
    'securityEngineer' : IDL.Null,
    'cybersecurityAnalyst' : IDL.Null,
    'softwareEngineer' : IDL.Null,
    'networkEngineer' : IDL.Null,
    'dataScientist' : IDL.Null,
  });
  const Time = IDL.Int;
  const GpsCoordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const JobApplication = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'role' : JobRole,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'locationLabel' : IDL.Opt(IDL.Text),
    'coverNote' : IDL.Text,
    'location' : IDL.Opt(GpsCoordinates),
    'resumeUrl' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const VisitorLog = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Opt(IDL.Float64),
    'locationAccess' : IDL.Bool,
    'longitude' : IDL.Opt(IDL.Float64),
    'timestamp' : Time,
    'userAgent' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockEmail' : IDL.Func([IDL.Text], [], []),
    'getAllApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
    'getBlockedEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTotalApplications' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitorLogs' : IDL.Func([], [IDL.Vec(VisitorLog)], ['query']),
    'isAcceptingApplications' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEmailBlocked' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'logVisitorLocation' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'logVisitorNoLocation' : IDL.Func([IDL.Text], [], []),
    'resetAdminClaim' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAcceptingApplications' : IDL.Func([IDL.Bool], [], []),
    'submitApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          JobRole,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'unblockEmail' : IDL.Func([IDL.Text], [], []),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };