/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApplicationStatus = { 'pending' : null } |
  { 'interview' : null } |
  { 'rejected' : null } |
  { 'reviewed' : null } |
  { 'offered' : null };
export interface GpsCoordinates { 'latitude' : number, 'longitude' : number }
export interface JobApplication {
  'id' : bigint,
  'status' : ApplicationStatus,
  'role' : JobRole,
  'fullName' : string,
  'email' : string,
  'timestamp' : Time,
  'locationLabel' : [] | [string],
  'coverNote' : string,
  'location' : [] | [GpsCoordinates],
  'resumeUrl' : string,
}
export type JobRole = { 'fullStackDeveloper' : null } |
  { 'securityEngineer' : null } |
  { 'cybersecurityAnalyst' : null } |
  { 'softwareEngineer' : null } |
  { 'networkEngineer' : null } |
  { 'dataScientist' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisitorLog {
  'id' : bigint,
  'latitude' : [] | [number],
  'locationAccess' : boolean,
  'longitude' : [] | [number],
  'timestamp' : Time,
  'userAgent' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockEmail' : ActorMethod<[string], undefined>,
  'getAllApplications' : ActorMethod<[], Array<JobApplication>>,
  'getBlockedEmails' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTotalApplications' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitorLogs' : ActorMethod<[], Array<VisitorLog>>,
  'isAcceptingApplications' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEmailBlocked' : ActorMethod<[string], boolean>,
  'logVisitorLocation' : ActorMethod<[number, number, string], undefined>,
  'logVisitorNoLocation' : ActorMethod<[string], undefined>,
  'resetAdminClaim' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAcceptingApplications' : ActorMethod<[boolean], undefined>,
  'submitApplication' : ActorMethod<
    [
      string,
      string,
      JobRole,
      string,
      string,
      [] | [number],
      [] | [number],
      [] | [string],
    ],
    bigint
  >,
  'unblockEmail' : ActorMethod<[string], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [bigint, ApplicationStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];