/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'interview' : IDL.Null,
  'rejected' : IDL.Null,
  'reviewed' : IDL.Null,
  'offered' : IDL.Null,
});
export const JobRole = IDL.Variant({
  'fullStackDeveloper' : IDL.Null,
  'securityEngineer' : IDL.Null,
  'cybersecurityAnalyst' : IDL.Null,
  'softwareEngineer' : IDL.Null,
  'networkEngineer' : IDL.Null,
  'dataScientist' : IDL.Null,
});
export const Time = IDL.Int;
export const JobApplication = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'role' : JobRole,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'coverNote' : IDL.Text,
  'resumeUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
  'getTotalApplications' : IDL.Func([], [IDL.Nat], ['query']),
  'isAcceptingApplications' : IDL.Func([], [IDL.Bool], ['query']),
  'setAcceptingApplications' : IDL.Func([IDL.Bool], [], []),
  'submitApplication' : IDL.Func(
      [IDL.Text, IDL.Text, JobRole, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'interview' : IDL.Null,
    'rejected' : IDL.Null,
    'reviewed' : IDL.Null,
    'offered' : IDL.Null,
  });
  const JobRole = IDL.Variant({
    'fullStackDeveloper' : IDL.Null,
    'securityEngineer' : IDL.Null,
    'cybersecurityAnalyst' : IDL.Null,
    'softwareEngineer' : IDL.Null,
    'networkEngineer' : IDL.Null,
    'dataScientist' : IDL.Null,
  });
  const Time = IDL.Int;
  const JobApplication = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'role' : JobRole,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'coverNote' : IDL.Text,
    'resumeUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
    'getTotalApplications' : IDL.Func([], [IDL.Nat], ['query']),
    'isAcceptingApplications' : IDL.Func([], [IDL.Bool], ['query']),
    'setAcceptingApplications' : IDL.Func([IDL.Bool], [], []),
    'submitApplication' : IDL.Func(
        [IDL.Text, IDL.Text, JobRole, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };