/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface GpsCoordinates {
    latitude: number;
    longitude: number;
}
export interface VisitorLog {
    id: bigint;
    latitude?: number;
    locationAccess: boolean;
    longitude?: number;
    timestamp: Time;
    userAgent: string;
}
export interface JobApplication {
    id: bigint;
    status: ApplicationStatus;
    role: JobRole;
    fullName: string;
    email: string;
    timestamp: Time;
    locationLabel?: string;
    coverNote: string;
    location?: GpsCoordinates;
    resumeUrl: string;
}
export interface UserProfile {
    name: string;
}
export enum ApplicationStatus {
    pending = "pending",
    interview = "interview",
    rejected = "rejected",
    reviewed = "reviewed",
    offered = "offered"
}
export enum JobRole {
    fullStackDeveloper = "fullStackDeveloper",
    securityEngineer = "securityEngineer",
    cybersecurityAnalyst = "cybersecurityAnalyst",
    softwareEngineer = "softwareEngineer",
    networkEngineer = "networkEngineer",
    dataScientist = "dataScientist"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    blockEmail(email: string): Promise<void>;
    getAllApplications(): Promise<Array<JobApplication>>;
    getBlockedEmails(): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getTotalApplications(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVisitorLogs(): Promise<Array<VisitorLog>>;
    isAcceptingApplications(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isEmailBlocked(email: string): Promise<boolean>;
    logVisitorLocation(latitude: number, longitude: number, userAgent: string): Promise<void>;
    logVisitorNoLocation(userAgent: string): Promise<void>;
    resetAdminClaim(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setAcceptingApplications(value: boolean): Promise<void>;
    submitApplication(fullName: string, email: string, role: JobRole, resumeUrl: string, coverNote: string, latitude: number | null, longitude: number | null, locationLabel: string | null): Promise<bigint>;
    unblockEmail(email: string): Promise<void>;
    updateApplicationStatus(id: bigint, newStatus: ApplicationStatus): Promise<void>;
}
import type { ApplicationStatus as _ApplicationStatus, GpsCoordinates as _GpsCoordinates, JobApplication as _JobApplication, JobRole as _JobRole, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VisitorLog as _VisitorLog } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockEmail(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockEmail(arg0);
            return result;
        }
    }
    async getAllApplications(): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApplications();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApplications();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlockedEmails(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockedEmails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockedEmails();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalApplications(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalApplications();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisitorLogs(): Promise<Array<VisitorLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitorLogs();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitorLogs();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAcceptingApplications(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAcceptingApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAcceptingApplications();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isEmailBlocked(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isEmailBlocked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isEmailBlocked(arg0);
            return result;
        }
    }
    async logVisitorLocation(arg0: number, arg1: number, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logVisitorLocation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logVisitorLocation(arg0, arg1, arg2);
            return result;
        }
    }
    async logVisitorNoLocation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logVisitorNoLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logVisitorNoLocation(arg0);
            return result;
        }
    }
    async resetAdminClaim(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAdminClaim();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAdminClaim();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setAcceptingApplications(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAcceptingApplications(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAcceptingApplications(arg0);
            return result;
        }
    }
    async submitApplication(arg0: string, arg1: string, arg2: JobRole, arg3: string, arg4: string, arg5: number | null, arg6: number | null, arg7: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitApplication(arg0, arg1, to_candid_JobRole_n19(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitApplication(arg0, arg1, to_candid_JobRole_n19(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async unblockEmail(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockEmail(arg0);
            return result;
        }
    }
    async updateApplicationStatus(arg0: bigint, arg1: ApplicationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ApplicationStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_JobApplication_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobApplication): JobApplication {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_JobRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobRole): JobRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_VisitorLog_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisitorLog): VisitorLog {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GpsCoordinates]): GpsCoordinates | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    latitude: [] | [number];
    locationAccess: boolean;
    longitude: [] | [number];
    timestamp: _Time;
    userAgent: string;
}): {
    id: bigint;
    latitude?: number;
    locationAccess: boolean;
    longitude?: number;
    timestamp: Time;
    userAgent: string;
} {
    return {
        id: value.id,
        latitude: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.latitude)),
        locationAccess: value.locationAccess,
        longitude: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.longitude)),
        timestamp: value.timestamp,
        userAgent: value.userAgent
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ApplicationStatus;
    role: _JobRole;
    fullName: string;
    email: string;
    timestamp: _Time;
    locationLabel: [] | [string];
    coverNote: string;
    location: [] | [_GpsCoordinates];
    resumeUrl: string;
}): {
    id: bigint;
    status: ApplicationStatus;
    role: JobRole;
    fullName: string;
    email: string;
    timestamp: Time;
    locationLabel?: string;
    coverNote: string;
    location?: GpsCoordinates;
    resumeUrl: string;
} {
    return {
        id: value.id,
        status: from_candid_ApplicationStatus_n6(_uploadFile, _downloadFile, value.status),
        role: from_candid_JobRole_n8(_uploadFile, _downloadFile, value.role),
        fullName: value.fullName,
        email: value.email,
        timestamp: value.timestamp,
        locationLabel: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.locationLabel)),
        coverNote: value.coverNote,
        location: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.location)),
        resumeUrl: value.resumeUrl
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    interview: null;
} | {
    rejected: null;
} | {
    reviewed: null;
} | {
    offered: null;
}): ApplicationStatus {
    return "pending" in value ? ApplicationStatus.pending : "interview" in value ? ApplicationStatus.interview : "rejected" in value ? ApplicationStatus.rejected : "reviewed" in value ? ApplicationStatus.reviewed : "offered" in value ? ApplicationStatus.offered : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fullStackDeveloper: null;
} | {
    securityEngineer: null;
} | {
    cybersecurityAnalyst: null;
} | {
    softwareEngineer: null;
} | {
    networkEngineer: null;
} | {
    dataScientist: null;
}): JobRole {
    return "fullStackDeveloper" in value ? JobRole.fullStackDeveloper : "securityEngineer" in value ? JobRole.securityEngineer : "cybersecurityAnalyst" in value ? JobRole.cybersecurityAnalyst : "softwareEngineer" in value ? JobRole.softwareEngineer : "networkEngineer" in value ? JobRole.networkEngineer : "dataScientist" in value ? JobRole.dataScientist : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VisitorLog>): Array<VisitorLog> {
    return value.map((x)=>from_candid_VisitorLog_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobApplication>): Array<JobApplication> {
    return value.map((x)=>from_candid_JobApplication_n4(_uploadFile, _downloadFile, x));
}
function to_candid_ApplicationStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): _ApplicationStatus {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_JobRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobRole): _JobRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobRole): {
    fullStackDeveloper: null;
} | {
    securityEngineer: null;
} | {
    cybersecurityAnalyst: null;
} | {
    softwareEngineer: null;
} | {
    networkEngineer: null;
} | {
    dataScientist: null;
} {
    return value == JobRole.fullStackDeveloper ? {
        fullStackDeveloper: null
    } : value == JobRole.securityEngineer ? {
        securityEngineer: null
    } : value == JobRole.cybersecurityAnalyst ? {
        cybersecurityAnalyst: null
    } : value == JobRole.softwareEngineer ? {
        softwareEngineer: null
    } : value == JobRole.networkEngineer ? {
        networkEngineer: null
    } : value == JobRole.dataScientist ? {
        dataScientist: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): {
    pending: null;
} | {
    interview: null;
} | {
    rejected: null;
} | {
    reviewed: null;
} | {
    offered: null;
} {
    return value == ApplicationStatus.pending ? {
        pending: null
    } : value == ApplicationStatus.interview ? {
        interview: null
    } : value == ApplicationStatus.rejected ? {
        rejected: null
    } : value == ApplicationStatus.reviewed ? {
        reviewed: null
    } : value == ApplicationStatus.offered ? {
        offered: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
